### ISSUE TITLE
Parser errors does not have the proper line number

### ISSUE THREAD

**Issue by gleamingthecube** [stephens2424/php#24]
Parser errors always display line=0 instead of the real line number.

**Comment by aayushranaut** [comment]
It seems to be working fine. Do you have code sample using which I can reproduce the issue?

**Comment by krageon** [comment]
Have a look at https://github.com/stephens2424/php/blob/master/parser/parser.go#L225

There is no way that works properly. Something along the lines of ```e.Line = p.current.Begin.Line``` does appear to work properly.

**Comment by stephens2424** [comment]
I think I broke this when I added support for multiple-file awareness in the parser.

**Comment by stephens2424** [comment]
Should be fixed now. Fixed the filenames too.
