### ISSUE TITLE
Lexer - Infinite loop on identifiers that contain multibyte runes

### ISSUE THREAD

**Issue by Briareos** [stephens2424/php#27]
The parser will hog the CPU when working on data like

    <?php
    $a = ‘test‘; // Note that ‘ is a 3-byte UTF-8 character %E2%80%98, not a single quote 

I get those files from users that copy-paste PHP code from online articles that apply formatting on PHP code. The reason it hangs is that [`*lexer.acceptRun`](https://github.com/stephens2424/php/blob/055c8fffe5dd014deeb80e0bf3736a3ffccb0ce7/lexer/lexer.go#L137) doesn't accept multibyte characters since they are not in the `valid` set. A quick fix I did was add an additional check for `utf8.RuneLen` to accept multibyte strings, but I'm not sure it's the best workaround.

**Comment by stephens2424** [comment]
Go ahead and give that a try. We're off the happy path here, so an error should still occur with that code, but not an infinite loop. :)

Thanks for the report!
