### ISSUE TITLE
Line-comments eat up everything on files using only carriage-return

### ISSUE THREAD

**Issue by Briareos** [stephens2424/php#29]
If the file uses only CR instead of LF/CRLF as line endings, the parser will treat everything after a line comment as part of that line comment.

Example (the `\r` character represents carriage-return, there's no `\n` anywhere in the file):

```php
<?php\r
// comment\r
$a = 1;
```

Will yield `// comment\r$a = 1;` as a line comment.

To fix that I changed
```go
func lexLineComment(l *lexer) stateFn {
    lineLength := strings.Index(l.input[l.pos:], "\n") + 1
```
to
```go
func lexLineComment(l *lexer) stateFn {
    lineLength := strings.IndexAny(l.input[l.pos:], "\r\n") + 1
```
and it seems to work fine.

**Comment by stephens2424** [comment]
Ah, yeah, I bet that fixes your particular case, but that there's also a few other usages of "\n" lurking around. Feel free to file a PR.
