### ISSUE TITLE
Lexer identifies class as Class token type in "$this->class" context.

### ISSUE THREAD

**Issue by SilbinaryWolf** [stephens2424/php#31]
Not sure if this intentional / a non-issue for your tooling, but I was hoping to iterate over each token to find out the class this way. Now I'm required to do additional ObjectOperator/ScopeResolutionOperator checks with the previous token.

**Comment by stephens2424** [comment]
Nope. That sounds like a bug. There are other cases I think it does catch, like `$null` recognizes `null` as an identifier in that context. Pushing up a fix.
